server:
  servlet:
    context-path: /identity-service
  port: 8080

spring:
  application:
    name: identity-service
  datasource:
    url: "jdbc:mysql://localhost:3309/identity_service"
    username: root
    password: root
  flyway:
    locations: classpath:/db/migration
    baseline-on-migrate: true
    baseline-version: 2
  jpa:
    show-sql: true
open:
  # http://localhost:8080/identity-service/swagger-ui/index.html#/user-controller
  api:
    title: API document
    description: description
    version: v1.0.0
jwt:
  signerKey: 24c0c34b24d56d2f9ff1a0de0433f7ff48e22aea8b8fec93b5f4a4298c88e431